"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Copy, Eye, Plus, RefreshCw, Trash2 } from "lucide-react";

type Program={id:string;name:string;updatedAt:string;createdAt:string;templates:{id:string;dayNumber:number;name:string;exercises:{id:string}[]}[]};

export default function AdminProgramsPage(){
 const [programs,setPrograms]=useState<Program[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
 async function load(){setLoading(true);setError("");try{const r=await fetch("/api/admin/workouts",{cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Impossibile caricare i programmi");setPrograms(Array.isArray(data.plans)?data.plans:[])}catch(e){setError(e instanceof Error?e.message:"Impossibile caricare i programmi")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function duplicate(id:string){setBusy(id);try{const r=await fetch(`/api/admin/workouts/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Impossibile duplicare il programma");await load()}catch(e){setError(e instanceof Error?e.message:"Impossibile duplicare il programma")}finally{setBusy("")}}
 async function remove(id:string,name:string){if(!window.confirm(`Eliminare definitivamente “${name}”?`))return;setBusy(id);try{const r=await fetch(`/api/admin/workouts/${id}`,{method:"DELETE"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Impossibile eliminare il programma");setPrograms(p=>p.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:"Impossibile eliminare il programma")}finally{setBusy("")}}
 return <main className="min-h-screen bg-[var(--background)] px-5 py-8 text-[var(--foreground)] md:px-10"><div className="mx-auto max-w-6xl">
  <Link href="/admin/exercises" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)]"><ArrowLeft size={16}/> Admin</Link>
  <header className="mt-7 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Admin / Programming</p><h1 className="mt-2 text-4xl font-black tracking-tight">Programmi</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Gestisci i programmi salvati, apri il dettaglio o crea una nuova scheda.</p></div><div className="flex gap-2"><button type="button" onClick={load} className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-black"><RefreshCw size={15}/> Aggiorna</button><Link href="/admin/workouts" className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-3 text-sm font-black text-[var(--accent-foreground)]"><Plus size={16}/> Nuovo programma</Link></div></header>
  {error&&<div className="mt-6 rounded-2xl border border-red-300 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}
  {loading?<div className="mt-8 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-8 text-sm text-[var(--muted)]">Caricamento programmi…</div>:programs.length===0?<div className="mt-8 rounded-[2rem] border border-dashed border-[var(--border)] bg-[var(--surface)] p-10 text-center"><p className="text-lg font-black">Nessun programma salvato</p><p className="mt-2 text-sm text-[var(--muted)]">Crea il primo programma dal Programming Studio.</p><Link href="/admin/workouts" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-black text-[var(--accent-foreground)]"><Plus size={16}/> Crea programma</Link></div>:<div className="mt-8 grid gap-4 md:grid-cols-2">{programs.map(p=>{const exerciseCount=p.templates.reduce((n,d)=>n+d.exercises.length,0);return <article key={p.id} className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">{p.name}</h2><p className="mt-2 text-xs font-bold text-[var(--muted)]">{p.templates.length} {p.templates.length===1?"giorno":"giorni"} · {exerciseCount} {exerciseCount===1?"esercizio":"esercizi"}</p></div><span className="rounded-full border px-3 py-1 text-[10px] font-black">Template</span></div><div className="mt-5 flex flex-wrap gap-2">{p.templates.slice(0,4).map(d=><span key={d.id} className="rounded-full bg-[var(--background)] px-3 py-1.5 text-[10px] font-black">G{d.dayNumber} · {d.name}</span>)}</div><p className="mt-5 text-[11px] font-bold text-[var(--muted)]">Modificato {new Date(p.updatedAt).toLocaleDateString("it-IT",{day:"2-digit",month:"short",year:"numeric"})}</p><div className="mt-5 flex flex-wrap gap-2 border-t border-[var(--border)] pt-4"><Link href={`/admin/programs/${p.id}`} className="inline-flex items-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-xs font-black text-[var(--accent-foreground)]"><Eye size={14}/> Apri</Link><button type="button" disabled={busy===p.id} onClick={()=>duplicate(p.id)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-black"><Copy size={14}/> {busy===p.id?"Attendi…":"Duplica"}</button><button type="button" disabled={busy===p.id} onClick={()=>remove(p.id,p.name)} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-black text-red-500"><Trash2 size={14}/> Elimina</button></div></article>})}</div>}
 </div></main>
}