"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, BarChart3, Scale, Trophy, Dumbbell } from "lucide-react";

type Data = { sessions: { id: string; startedAt: string; completedAt: string | null; plan: { name: string } }[]; sets: { id: string; exerciseId: string; setNumber: number; weight: number; reps: number; rir: number | null; timestamp: string; exercise: { name: string } }[]; weights: { id: string; weightKg: number; recordedAt: string }[]; weekly: { label: string; count: number }[]; records: { name: string; weight: number; reps: number; volume: number }[] };

export default function ProgressPage() { const [data,setData]=useState<Data|null>(null); const [loading,setLoading]=useState(true); useEffect(()=>{fetch("/api/progress").then(async r=>{const d=await r.json();if(!r.ok) throw new Error(d.error||"Errore");return d}).then(setData).catch(()=>setData({sessions:[],sets:[],weights:[],weekly:[],records:[]})).finally(()=>setLoading(false));},[]); const max=Math.max(1,...(data?.weekly.map(w=>w.count)||[1])); const current=data?.weights.at(-1)?.weightKg; const previous=data?.weights.length && data.weights.length>1 ? data.weights[data.weights.length-2].weightKg : undefined; const change=current!=null&&previous!=null?current-previous:null; return <main className="min-h-screen bg-[var(--background)] pb-12"><div className="mx-auto max-w-5xl px-5 py-6 sm:px-8"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)]"><ArrowLeft size={17}/> Dashboard</Link><header className="mt-8"><p className="text-xs font-black tracking-[0.2em] text-[var(--accent)]">YOUR PROGRESS</p><h1 className="mt-2 text-4xl font-black">Il lavoro diventa progresso.</h1><p className="mt-2 text-sm text-[var(--muted)]">Serie, carichi, costanza e peso vengono registrati dai tuoi allenamenti.</p></header>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat icon={<Dumbbell/>} value={String(data?.sessions.length ?? 0)} label="Allenamenti completati"/><Stat icon={<Scale/>} value={current!=null?`${current} kg`:"—"} label={change==null?"Peso attuale":`${change>0?"+":""}${change.toFixed(1)} kg dall'ultima misura`}/><Stat icon={<Trophy/>} value={String(data?.records.length ?? 0)} label="Record esercizi"/></div>
    <section className="mt-5 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[0.18em] text-[var(--accent)]">ULTIME 8 SETTIMANE</p><h2 className="mt-2 text-2xl font-black">Costanza</h2></div><span className="text-sm font-bold text-[var(--muted)]">{data?.sessions.length ?? 0} workout</span></div><div className="mt-8 grid h-44 grid-cols-8 items-end gap-2">{(data?.weekly||[]).map((w,i)=><div key={i} className="flex h-full flex-col items-center justify-end gap-2"><div className="w-full rounded-t-xl bg-[var(--accent)]" style={{height:`${Math.max(8,(w.count/max)*100)}%`}}/><span className="text-[9px] font-bold text-[var(--muted)]">{w.label}</span></div>)}</div></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><Trophy size={19} className="text-[var(--accent)]"/><h2 className="text-xl font-black">Migliori performance</h2></div>{data?.records.length ? <div className="mt-5 space-y-2">{data.records.map(r=><div key={r.name} className="flex items-center justify-between rounded-2xl bg-[var(--surface-strong)] px-4 py-3"><div><p className="text-sm font-black">{r.name}</p><p className="text-xs text-[var(--muted)]">{r.reps} reps</p></div><span className="text-sm font-black text-[var(--accent)]">{r.weight} kg</span></div>)}</div> : <p className="mt-5 text-sm text-[var(--muted)]">Completa qualche serie per vedere le tue migliori performance.</p>}</section><section className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6"><div className="flex items-center gap-2"><BarChart3 size={19} className="text-[var(--accent)]"/><h2 className="text-xl font-black">Storico serie</h2></div>{data?.sets.length ? <div className="mt-5 space-y-2">{data.sets.slice(0,8).map(s=><div key={s.id} className="flex items-center justify-between rounded-2xl bg-[var(--surface-strong)] px-4 py-3"><div><p className="text-sm font-black">{s.exercise.name}</p><p className="text-xs text-[var(--muted)]">{new Date(s.timestamp).toLocaleDateString("it-IT")}</p></div><span className="text-sm font-black">{s.weight} kg × {s.reps}</span></div>)}</div> : <p className="mt-5 text-sm text-[var(--muted)]">Le serie che registrerai durante gli allenamenti appariranno qui.</p>}</section></div>
    {loading&&<p className="mt-5 text-center text-xs font-bold text-[var(--muted)]">Caricamento progressi...</p>}
  </div></main>; }
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6"><div className="text-[var(--accent)]">{icon}</div><p className="mt-7 text-3xl font-black">{value}</p><p className="mt-1 text-sm text-[var(--muted)]">{label}</p></div>}
