"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ChevronDown, ChevronUp, Copy, GripVertical, Plus, Save, Trash2 } from "lucide-react";

type Exercise={id:string;name:string;primaryMuscles:string;difficulty:string};
type Item={exerciseId:string;sets:number;repMin:number;repMax:number;rirTarget:number|string;restSeconds:number;mode:string};
type Day={name:string;estimatedMins:number;exercises:Item[]};
const blankDay=():Day=>({name:"",estimatedMins:45,exercises:[]});
const modes=["NORMAL","WARM_UP","SUPERSET","GIANT_SET","CIRCUIT","DROP_SET","FINISHER"];
const restOptions=[45,60,75,90,120,150,180,240];
const repOptions=["4–6","6–8","8–10","8–12","10–12","10–15","12–15","15–20"];
const modeLabel:Record<string,string>={NORMAL:"Serie normale",WARM_UP:"Warm-up",SUPERSET:"Superset",GIANT_SET:"Giant set",CIRCUIT:"Circuito",DROP_SET:"Drop set",FINISHER:"Finisher"};
export default function AdminWorkoutsPage(){
 const [exercises,setExercises]=useState<Exercise[]>([]); const [name,setName]=useState(""); const [days,setDays]=useState<Day[]>([blankDay()]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [drag,setDrag]=useState<{day:number;item:number}|null>(null);
 useEffect(()=>{fetch("/api/admin/workouts").then(r=>r.json()).then(d=>setExercises(d.exercises??[])).catch(()=>setMessage("Impossibile caricare gli esercizi")).finally(()=>setLoading(false))},[]);
 const updateDay=(di:number,patch:Partial<Day>)=>setDays(ds=>ds.map((d,i)=>i===di?{...d,...patch}:d));
 const addExercise=(di:number,id:string)=>{if(!id)return;setDays(ds=>ds.map((d,i)=>i===di?{...d,exercises:[...d.exercises,{exerciseId:id,sets:3,repMin:8,repMax:10,rirTarget:2,restSeconds:90,mode:"NORMAL"}]}:d))};
 const updateItem=(di:number,ii:number,patch:Partial<Item>)=>setDays(ds=>ds.map((d,i)=>i===di?{...d,exercises:d.exercises.map((x,j)=>j===ii?{...x,...patch}:x)}:d));
 const removeItem=(di:number,ii:number)=>setDays(ds=>ds.map((d,i)=>i===di?{...d,exercises:d.exercises.filter((_,j)=>j!==ii)}:d));
 const moveItem=(di:number,ii:number,dir:-1|1)=>setDays(ds=>ds.map((d,i)=>{if(i!==di)return d;const to=ii+dir;if(to<0||to>=d.exercises.length)return d;const a=[...d.exercises];[a[ii],a[to]]=[a[to],a[ii]];return {...d,exercises:a}}));
 const duplicateItem=(di:number,ii:number)=>setDays(ds=>ds.map((d,i)=>i!==di?d:{...d,exercises:[...d.exercises.slice(0,ii+1),{...d.exercises[ii]},...d.exercises.slice(ii+1)]}));
 const duplicateDay=(di:number)=>setDays(ds=>{const copy={...ds[di],name:`${ds[di].name||`Day ${di+1}`} · Copy`,exercises:ds[di].exercises.map(x=>({...x}))};return [...ds.slice(0,di+1),copy,...ds.slice(di+1)]});
 const dropItem=(targetDay:number,targetItem:number)=>{if(!drag)return;setDays(ds=>{const next=ds.map(d=>({...d,exercises:[...d.exercises]}));const [moved]=next[drag.day].exercises.splice(drag.item,1);let insert=targetItem;if(drag.day===targetDay&&drag.item<targetItem)insert--;next[targetDay].exercises.splice(Math.max(0,insert),0,moved);return next});setDrag(null)};
 const applyRepPreset=(di:number,ii:number,v:string)=>{const [a,b]=v.split("–").map(Number);updateItem(di,ii,{repMin:a,repMax:b})};
 async function save(){if(!name.trim()||days.length===0)return;setSaving(true);setMessage("");try{const r=await fetch("/api/admin/workouts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,days})});const data=await r.json();if(!r.ok)throw Error(data.error||"Errore");setMessage("✓ Scheda salvata");setName("");setDays([blankDay()])}catch(e){setMessage(e instanceof Error?e.message:"Errore durante il salvataggio")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[var(--background)] px-5 py-8 text-[var(--foreground)] md:px-10"><div className="mx-auto max-w-6xl"><Link href="/admin/exercises" className="inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)]"><ArrowLeft size={16}/> Exercise Library</Link><header className="mt-7"><p className="text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Admin / Programming</p><h1 className="mt-2 text-4xl font-black tracking-tight">Workout Programming Studio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">Costruisci programmi completi partendo dalla Exercise Library. Ogni giornata resta separata e ogni esercizio può avere una logica di lavoro diversa.</p></header>
 <section className="mt-7 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><div className="grid gap-5 md:grid-cols-[1fr_auto]"><label className="text-xs font-black uppercase tracking-wide text-[var(--muted)]">Nome programma<input value={name} onChange={e=>setName(e.target.value)} placeholder="Full Body · Foundation" className="field mt-2"/></label><div className="rounded-2xl bg-[var(--background)] px-5 py-4 text-center"><div className="text-2xl font-black">{days.length}</div><div className="text-[10px] font-black uppercase text-[var(--muted)]">giorni</div></div></div></section>
 <div className="mt-5 space-y-5">{days.map((day,di)=><section key={di} className="rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="grid flex-1 gap-3 sm:grid-cols-[1fr_140px]"><label className="text-xs font-black text-[var(--muted)]">GIORNO {di+1}<input value={day.name} onChange={e=>updateDay(di,{name:e.target.value})} placeholder="Push · Upper body" className="field mt-2"/></label><label className="text-xs font-black text-[var(--muted)]">DURATA · MIN<input type="number" min="1" value={day.estimatedMins} onChange={e=>updateDay(di,{estimatedMins:Number(e.target.value)})} className="field mt-2"/></label></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>duplicateDay(di)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-black"><Copy size={14}/> Duplica</button>{days.length>1&&<button type="button" onClick={()=>setDays(ds=>ds.filter((_,i)=>i!==di))} className="rounded-xl border px-3 py-2 text-xs font-black text-red-500">Rimuovi</button>}</div></div>
 <div className="mt-6 space-y-3">{day.exercises.map((item,ii)=>{const ex=exercises.find(x=>x.id===item.exerciseId);return <div key={`${item.exerciseId}-${ii}`} draggable onDragStart={()=>setDrag({day:di,item:ii})} onDragOver={e=>e.preventDefault()} onDrop={()=>dropItem(di,ii)} className="group rounded-2xl border border-[var(--border)] bg-[var(--background)] p-4"><div className="flex items-start gap-3"><div className="flex items-center gap-1 pt-1"><GripVertical size={18} className="cursor-grab text-[var(--muted)]"/><div className="hidden flex-col gap-1 sm:flex"><button type="button" onClick={()=>moveItem(di,ii,-1)} className="rounded-lg border p-1" disabled={ii===0}><ChevronUp size={13}/></button><button type="button" onClick={()=>moveItem(di,ii,1)} className="rounded-lg border p-1" disabled={ii===day.exercises.length-1}><ChevronDown size={13}/></button></div></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-black">{ex?.name??"Exercise"}</p><span className="rounded-full bg-[var(--accent)]/10 px-2 py-1 text-[10px] font-black">{ex?.primaryMuscles}</span><span className="rounded-full border px-2 py-1 text-[10px] font-bold">{modeLabel[item.mode]}</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-6"><label className="text-[10px] font-black text-[var(--muted)]">SERIE<input type="number" min="1" value={item.sets} onChange={e=>updateItem(di,ii,{sets:Number(e.target.value)})} className="field mt-1"/></label><label className="text-[10px] font-black text-[var(--muted)]">RANGE REP<select value={`${item.repMin}–${item.repMax}`} onChange={e=>applyRepPreset(di,ii,e.target.value)} className="field mt-1">{repOptions.map(v=><option key={v}>{v}</option>)}</select></label><label className="text-[10px] font-black text-[var(--muted)]">RIR<input type="number" min="0" max="5" step="0.5" value={item.rirTarget} onChange={e=>updateItem(di,ii,{rirTarget:e.target.value})} className="field mt-1"/></label><label className="text-[10px] font-black text-[var(--muted)]">RECUPERO<select value={item.restSeconds} onChange={e=>updateItem(di,ii,{restSeconds:Number(e.target.value)})} className="field mt-1">{restOptions.map(v=><option key={v} value={v}>{v}s</option>)}</select></label><label className="text-[10px] font-black text-[var(--muted)] sm:col-span-2">TIPO DI LAVORO<select value={item.mode} onChange={e=>updateItem(di,ii,{mode:e.target.value})} className="field mt-1">{modes.map(v=><option key={v} value={v}>{modeLabel[v]}</option>)}</select></label></div></div><div className="flex gap-1"><button type="button" title="Duplica esercizio" onClick={()=>duplicateItem(di,ii)} className="rounded-xl border p-2"><Copy size={15}/></button><button type="button" title="Elimina" onClick={()=>removeItem(di,ii)} className="rounded-xl border p-2 text-red-500"><Trash2 size={15}/></button></div></div></div>})}</div>
 <div className="mt-4 flex flex-col gap-3 sm:flex-row"><select defaultValue="" onChange={e=>{addExercise(di,e.target.value);e.currentTarget.value=""}} className="field flex-1"><option value="" disabled>+ Aggiungi esercizio dalla Library</option>{exercises.map(e=><option key={e.id} value={e.id}>{e.name} · {e.primaryMuscles}</option>)}</select><span className="inline-flex items-center justify-center rounded-xl border px-4 py-2 text-xs font-bold text-[var(--muted)]">{day.exercises.length} esercizi</span></div></section>)}
 <button type="button" onClick={()=>setDays(ds=>[...ds,blankDay()])} className="inline-flex items-center gap-2 rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-5 py-3 text-sm font-black"><Plus size={17}/> Aggiungi giorno</button></div>
 <div className="sticky bottom-4 mt-6 flex items-center justify-between gap-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)]/95 p-3 shadow-xl"><span className={`text-sm font-bold ${message.startsWith("✓")?"text-green-600":"text-red-500"}`}>{message}</span><button type="button" disabled={saving||loading||!name.trim()} onClick={save} className="inline-flex items-center gap-2 rounded-2xl bg-[var(--accent)] px-6 py-3 text-sm font-black text-[var(--accent-foreground)] disabled:opacity-50"><Save size={16}/>{saving?"Salvataggio…":"Salva programma"}</button></div></div></main>;
}
