"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { BarChart3, CalendarDays, Dumbbell, Flame, Play, TrendingUp, UserRound } from "lucide-react";

type Data = { plan: { id: string; name: string; templates: { id: string; dayNumber: number; name: string; estimatedMins: number | null; exercises: { id: string; sets: number; repMin: number; repMax: number; exercise: { name: string } }[] }[] } | null; sessions: { id: string; startedAt: string; completedAt: string | null }[]; nextSchedule: { id: string; scheduledDate: string; template: { id: string; dayNumber: number; name: string; estimatedMins: number | null; exercises: { id: string }[] } } | null };
const navItems = [["Dashboard", "/dashboard", BarChart3], ["Progress", "/progress", TrendingUp], ["Calendario", "/calendar", CalendarDays], ["Profilo", "/profile", UserRound]] as const;

export default function DashboardPage() {
  const [user, setUser] = useState<{ firstName: string } | null>(null); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/auth/me").then(r => r.json()).then(d => { if (!d.user) { window.location.href = "/login?next=/dashboard"; return; } if (!d.user.onboarding?.completedAt) { window.location.href = "/onboarding"; return; } setUser({ firstName: d.user.profile?.firstName?.trim() || "Athlete" }); }); }, []);
  useEffect(() => { const now = new Date(); fetch(`/api/workouts/dashboard?year=${now.getFullYear()}&month=${now.getMonth()}`).then(r => r.json()).then(setData).finally(() => setLoading(false)); }, []);
  if (!user) return <main className="min-h-screen p-8 text-sm text-[var(--muted)]">Caricamento...</main>;
  const next = data?.nextSchedule;
  return <main className="min-h-screen bg-[var(--background)] pb-28"><div className="mx-auto w-full max-w-6xl px-5 py-6 sm:px-8 lg:px-10">
    <header className="flex items-center justify-between gap-4"><div><p className="text-xs font-black tracking-[0.25em] text-[var(--accent)]">GYM PROGRESS</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Ciao, {user.firstName}.</h1><p className="mt-1 text-sm text-[var(--muted)]">{next ? "Hai già programmato il tuo prossimo allenamento." : "Apri il Calendario per decidere quando allenarti."}</p></div><Link href="/profile" aria-label="Profilo" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface)] text-[var(--accent)]"><UserRound size={19}/></Link></header>
    <section className="mt-8 rounded-[2rem] bg-[var(--accent)] p-6 text-[var(--accent-foreground)] shadow-2xl sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black tracking-[0.2em] opacity-70"><Flame size={16}/> {next ? "PROSSIMO ALLENAMENTO" : "INIZIA DAL CALENDARIO"}</div><h2 className="mt-3 text-3xl font-black sm:text-4xl">{next?.template.name || "Programma il tuo prossimo workout"}</h2><p className="mt-2 max-w-xl text-sm font-medium leading-6 opacity-75">{next ? `${new Date(next.scheduledDate).toLocaleDateString("it-IT", { weekday: "long", day: "numeric", month: "long" })} · ${next.template.exercises.length} esercizi${next.template.estimatedMins ? ` · circa ${next.template.estimatedMins} min` : ""}` : "Scegli una data, associa un giorno della scheda e poi apri il workout da lì."}</p></div><Link href={next ? `/workout?day=${next.template.dayNumber}&date=${next.scheduledDate.slice(0,10)}` : "/calendar"} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[var(--accent-foreground)] px-5 py-3.5 text-sm font-black"><Play size={16} fill="currentColor"/> {next ? "VEDI WORKOUT" : "APRI CALENDARIO"}</Link></div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Link href="/calendar" className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 transition hover:border-[var(--accent)]"><CalendarDays className="text-[var(--accent)]" size={20}/><p className="mt-4 text-lg font-black">Calendario</p><p className="mt-1 text-sm text-[var(--muted)]">Pianifica e controlla ogni allenamento.</p></Link><Link href="/progress" className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5 transition hover:border-[var(--accent)]"><TrendingUp className="text-[var(--accent)]" size={20}/><p className="mt-4 text-lg font-black">Progressi</p><p className="mt-1 text-sm text-[var(--muted)]">Controlla costanza e risultati.</p></Link><div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><Dumbbell className="text-[var(--accent)]" size={20}/><p className="mt-4 text-lg font-black">Programma</p><p className="mt-1 text-sm text-[var(--muted)]">{data?.plan ? `${data.plan.templates.length} giorni · ${data.plan.name}` : loading ? "Caricamento..." : "Nessun programma assegnato"}</p></div></section>
    <section className="mt-6 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black tracking-[0.18em] text-[var(--accent)]">ULTIMI ALLENAMENTI</p><h2 className="mt-2 text-2xl font-black">La tua attività</h2></div><Link href="/progress" className="text-xs font-black text-[var(--accent)]">Vedi progressi</Link></div>{data?.sessions.length ? <div className="mt-5 space-y-2">{data.sessions.slice(-5).reverse().map(s => <div key={s.id} className="flex items-center justify-between rounded-2xl bg-[var(--surface-strong)] px-4 py-3"><span className="text-sm font-bold">{new Date(s.startedAt).toLocaleDateString("it-IT", { day: "numeric", month: "short" })}</span><span className="text-xs font-black text-[var(--accent)]">{s.completedAt ? "COMPLETATO" : "IN CORSO"}</span></div>)}</div> : <p className="mt-5 text-sm text-[var(--muted)]">Ancora nessun allenamento registrato. Quando inizi, lo vedrai qui.</p>}</section>
    <nav className="fixed inset-x-0 bottom-4 z-20 mx-auto flex w-[calc(100%-2rem)] max-w-md items-center justify-around rounded-3xl border border-[var(--border)] bg-[var(--surface)]/95 p-2 shadow-2xl backdrop-blur-xl">{navItems.map(([label, href, Icon]) => <Link key={label} href={href} className={`flex min-w-16 flex-col items-center gap-1 rounded-2xl px-3 py-2 text-[10px] font-bold ${href === "/dashboard" ? "bg-[var(--accent)] text-[var(--accent-foreground)]" : "text-[var(--muted)]"}`}><Icon size={17}/>{label}</Link>)}</nav>
  </div></main>;
}
