"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, ChevronLeft, ChevronRight, Dumbbell, Flame, Play, Target, TrendingUp, UserRound } from "lucide-react";

const navItems = [["Dashboard", "/dashboard", BarChart3], ["Workout", "/workout", Play], ["Progress", "/progress", TrendingUp], ["Profile", "/profile", UserRound]] as const;
type Data = { plan: { id: string; name: string; templates: { id: string; dayNumber: number; name: string; estimatedMins: number | null; exercises: { id: string; sets: number; repMin: number; repMax: number; exercise: { name: string } }[] }[] } | null; sessions: { id: string; startedAt: string; completedAt: string | null }[]; nextTemplate: { id: string; dayNumber: number; name: string; estimatedMins: number | null; exercises: { id: string; sets: number; repMin: number; repMax: number; exercise: { name: string } }[] } | null };

function sameDay(a: Date, b: Date) { return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate(); }
function monthDays(date: Date) { const first = new Date(date.getFullYear(), date.getMonth(), 1); const count = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); const offset = (first.getDay() + 6) % 7; return [...Array(offset).fill(null), ...Array.from({ length: count }, (_, i) => new Date(date.getFullYear(), date.getMonth(), i + 1))]; }

export default function DashboardPage() {
  const [user, setUser] = useState<{ firstName: string } | null>(null); const [date, setDate] = useState(new Date()); const [selected, setSelected] = useState(new Date()); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/auth/me").then(r => r.json()).then(d => { if (!d.user) { window.location.href = "/login?next=/dashboard"; return; } if (!d.user.onboarding?.completedAt) { window.location.href = "/onboarding"; return; } setUser({ firstName: d.user.profile?.firstName?.trim() || "Athlete" }); }); }, []);
  useEffect(() => { setLoading(true); fetch(`/api/workouts/dashboard?year=${date.getFullYear()}&month=${date.getMonth()}`).then(r => r.json()).then(setData).finally(() => setLoading(false)); }, [date]);
  const days = useMemo(() => monthDays(date), [date]); const today = new Date(); const selectedSession = data?.sessions.find(s => sameDay(new Date(s.startedAt), selected)); const selectedIsToday = sameDay(selected, today); const canStart = !!data?.plan && !!data?.nextTemplate;
  if (!user) return <main className="min-h-screen p-8 text-sm text-[var(--muted)]">Caricamento...</main>;
  return <main className="min-h-screen bg-[var(--background)] pb-28"><div className="mx-auto w-full max-w-6xl px-5 py-6 sm:px-8 lg:px-10">
    <header className="flex items-center justify-between gap-4"><div><p className="text-xs font-black tracking-[0.25em] text-[var(--accent)]">GYM PROGRESS</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Ciao, {user.firstName}.</h1><p className="mt-1 text-sm text-[var(--muted)]">Scegli quando vuoi allenarti.</p></div><Link href="/profile" aria-label="Profile" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface)] text-[var(--accent)]"><UserRound size={19}/></Link></header>
    <section className="mt-8 rounded-[2rem] bg-[var(--accent)] p-6 text-[var(--accent-foreground)] shadow-2xl sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-black tracking-[0.2em] opacity-70"><Flame size={16}/> {selectedIsToday ? "OGGI" : selected.toLocaleDateString("it-IT", { weekday: "long" }).toUpperCase()}</div><h2 className="mt-3 text-3xl font-black sm:text-4xl">{selectedSession?.completedAt ? "Allenamento completato" : data?.nextTemplate ? data.nextTemplate.name : "Nessun programma attivo"}</h2><p className="mt-2 max-w-xl text-sm font-medium leading-6 opacity-75">{selectedSession?.completedAt ? "Hai già completato la sessione di questo giorno." : data?.nextTemplate ? `${data.nextTemplate.exercises.length} esercizi${data.nextTemplate.estimatedMins ? ` · circa ${data.nextTemplate.estimatedMins} min` : ""}. Puoi allenarti nella data che preferisci.` : "Quando ti verrà assegnato un programma, lo vedrai qui."}</p></div>{canStart && !selectedSession?.completedAt && <Link href={`/workout?date=${selected.toISOString().slice(0,10)}&day=${data.nextTemplate?.dayNumber}`} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-[var(--accent-foreground)] px-5 py-3.5 text-sm font-black"><Play size={16} fill="currentColor"/> INIZIA</Link>}</div></section>
    <section className="mt-6 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-black tracking-[0.18em] text-[var(--accent)]">CALENDARIO</p><h2 className="mt-1 text-2xl font-black">Quando vuoi allenarti</h2></div><div className="flex items-center gap-2"><button aria-label="Mese precedente" onClick={() => setDate(new Date(date.getFullYear(), date.getMonth() - 1, 1))} className="rounded-xl border border-[var(--border)] p-2"><ChevronLeft size={18}/></button><button onClick={() => { const n = new Date(); setDate(n); setSelected(n); }} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-black">OGGI</button><button aria-label="Mese successivo" onClick={() => setDate(new Date(date.getFullYear(), date.getMonth() + 1, 1))} className="rounded-xl border border-[var(--border)] p-2"><ChevronRight size={18}/></button></div></div><div className="mt-5 grid grid-cols-7 gap-1 text-center text-[10px] font-black uppercase tracking-wider text-[var(--muted)] sm:gap-2">{["Lun","Mar","Mer","Gio","Ven","Sab","Dom"].map(d => <div key={d} className="py-2">{d}</div>)}{days.map((day, i) => { if (!day) return <div key={`empty-${i}`}/>; const session = data?.sessions.find(s => sameDay(new Date(s.startedAt), day)); const isSelected = sameDay(day, selected); const isToday = sameDay(day, today); return <button key={day.toISOString()} onClick={() => setSelected(day)} className={`relative min-h-16 rounded-2xl p-2 text-left transition ${isSelected ? "ring-2 ring-[var(--accent)]" : "border border-[var(--border)]"} ${isToday ? "bg-[var(--surface-strong)]" : "bg-[var(--background)]"}`}><span className="text-sm font-black">{day.getDate()}</span>{session?.completedAt ? <span className="absolute bottom-2 left-2 right-2 rounded-full bg-[var(--accent)] px-1.5 py-0.5 text-center text-[9px] font-black text-[var(--accent-foreground)]">COMPLETATO</span> : <span className="absolute bottom-2 left-2 right-2 text-[9px] font-bold text-[var(--muted)]">{sameDay(day, today) ? "OGGI" : ""}</span>}</button>; })}</div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><CalendarDays className="text-[var(--accent)]" size={19}/><p className="mt-4 text-2xl font-black">{data?.plan?.templates.length ?? 0}</p><p className="mt-1 text-xs text-[var(--muted)]">giorni nel programma</p></div><div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><Dumbbell className="text-[var(--accent)]" size={19}/><p className="mt-4 text-2xl font-black">{data?.nextTemplate?.exercises.length ?? 0}</p><p className="mt-1 text-xs text-[var(--muted)]">esercizi prossima sessione</p></div><div className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><Target className="text-[var(--accent)]" size={19}/><p className="mt-4 text-2xl font-black">{loading ? "—" : data?.sessions.filter(s => s.completedAt).length ?? 0}</p><p className="mt-1 text-xs text-[var(--muted)]">sessioni completate nel mese</p></div></section>
    <nav className="fixed inset-x-0 bottom-4 z-20 mx-auto flex w-[calc(100%-2rem)] max-w-md items-center justify-around rounded-3xl border border-[var(--border)] bg-[var(--surface)]/95 p-2 shadow-2xl backdrop-blur-xl">{navItems.map(([label, href, Icon], index) => <Link key={label} href={href} className={`flex min-w-16 flex-col items-center gap-1 rounded-2xl px-3 py-2 text-[10px] font-bold ${index === 0 ? "bg-[var(--accent)] text-[var(--accent-foreground)]" : "text-[var(--muted)]"}`}><Icon size={17}/>{label}</Link>)}</nav>
  </div></main>;
}
