"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { CalendarDays, CheckCircle2, Clock3, Users } from "lucide-react";

type Session = { id: string; startedAt: string; completedAt: string | null; user: { id: string; email: string; profile: { firstName: string | null } | null }; plan: { id: string; name: string } };

function dayKey(value: string | Date) { const d = typeof value === "string" ? new Date(value) : value; return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function initials(s: Session) { return (s.user.profile?.firstName?.trim() || s.user.email.split("@")[0]).slice(0,1).toUpperCase(); }

export default function AdminCalendarPage() {
  const [sessions,setSessions]=useState<Session[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [cursor,setCursor]=useState(()=>new Date()); const [selected,setSelected]=useState(dayKey(new Date()));
  useEffect(()=>{fetch("/api/admin/calendar").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Errore calendario");return d.sessions}).then(setSessions).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  const monthDays=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate();return [...Array(start).fill(null),...Array.from({length:last},(_,i)=>new Date(y,m,i+1))]},[cursor]);
  const byDay=useMemo(()=>{const map:Record<string,Session[]>= {};sessions.forEach(s=>(map[dayKey(s.startedAt)]??=[]).push(s));return map},[sessions]);
  const selectedSessions=byDay[selected]||[]; const monthLabel=cursor.toLocaleDateString("it-IT",{month:"long",year:"numeric"});
  return <main className="min-h-screen px-5 py-8 md:px-10"><div className="mx-auto max-w-7xl"><header className="mb-7 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="mb-2 text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">Monitoraggio</p><h1 className="text-3xl font-black md:text-4xl">Calendario</h1><p className="mt-1 text-sm text-[var(--muted)]">Allenamenti registrati dagli utenti.</p></div><div className="flex items-center gap-2"><button className="btn-surface px-3 py-2 text-sm font-black" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}>←</button><button className="btn-surface px-4 py-2 text-sm font-black" onClick={()=>{const n=new Date();setCursor(n);setSelected(dayKey(n))}}>Oggi</button><button className="btn-surface px-3 py-2 text-sm font-black" onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}>→</button></div></header>
  {error&&<div className="mb-5 rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm font-bold">{error}</div>}
  <div className="grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-4 md:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="capitalize text-lg font-black">{monthLabel}</h2><div className="flex gap-4 text-[10px] font-black uppercase tracking-wider text-[var(--muted)]"><span>● Allenamento</span><span>✓ Completato</span></div></div><div className="grid grid-cols-7 gap-1 text-center text-[10px] font-black uppercase tracking-wider text-[var(--muted)] sm:gap-2">{["Lun","Mar","Mer","Gio","Ven","Sab","Dom"].map(d=><div key={d} className="pb-2">{d}</div>)}{monthDays.map((date,i)=>{if(!date)return <div key={`empty-${i}`} className="min-h-20 rounded-2xl"/>;const k=dayKey(date),items=byDay[k]||[],active=k===selected;return <button key={k} onClick={()=>setSelected(k)} className={`min-h-20 rounded-2xl border p-2 text-left transition ${active?"border-[var(--accent)] bg-[var(--accent)]/10":"border-[var(--border)] bg-[var(--surface-strong)] hover:border-[var(--accent)]/50"}`}><div className="flex items-center justify-between"><span className="text-sm font-black">{date.getDate()}</span>{items.length>0&&<span className="rounded-full bg-[var(--accent)] px-1.5 py-0.5 text-[9px] font-black text-black">{items.length}</span>}</div><div className="mt-3 space-y-1">{items.slice(0,2).map(s=><div key={s.id} className="truncate text-[9px] font-bold">{s.completedAt?"✓":"•"} {s.user.profile?.firstName||s.user.email.split("@")[0]}</div>)}</div></button>})}</div></section>
  <aside className="rounded-3xl border border-[var(--border)] bg-[var(--surface)] p-5"><div className="mb-5 flex items-center gap-2"><CalendarDays size={19} className="text-[var(--accent)]"/><div><p className="text-xs font-black uppercase tracking-wider text-[var(--muted)]">Selezionato</p><h2 className="font-black">{new Date(`${selected}T12:00:00`).toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"})}</h2></div></div>{loading?<p className="text-sm text-[var(--muted)]">Caricamento...</p>:selectedSessions.length===0?<div className="rounded-2xl bg-[var(--surface-strong)] p-5 text-center"><Clock3 className="mx-auto mb-2 text-[var(--muted)]" size={20}/><p className="text-sm font-bold">Nessun allenamento</p><p className="mt-1 text-xs text-[var(--muted)]">Nessuna sessione registrata per questa data.</p></div>:<div className="space-y-3">{selectedSessions.map(s=><Link href={`/admin/users/${s.user.id}`} key={s.id} className="block rounded-2xl border border-[var(--border)] bg-[var(--surface-strong)] p-4 hover:border-[var(--accent)]/60"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{s.user.profile?.firstName||s.user.email.split("@")[0]}</p><p className="mt-1 text-xs text-[var(--muted)]">{s.plan.name}</p></div>{s.completedAt?<CheckCircle2 size={18} className="shrink-0 text-[var(--accent)]"/>:<Clock3 size={18} className="shrink-0 text-[var(--muted)]"/>}</div><p className="mt-3 text-[10px] font-black uppercase tracking-wider text-[var(--muted)]">{new Date(s.startedAt).toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"})} · {s.completedAt?"Completato":"In corso"}</p></Link>)}</div>}{selectedSessions.length>0&&<div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-[var(--surface-strong)] p-3"><Users size={15} className="mb-2 text-[var(--accent)]"/><p className="text-[10px] font-black uppercase tracking-wider text-[var(--muted)]">Sessioni</p><p className="text-lg font-black">{selectedSessions.length}</p></div><div className="rounded-2xl bg-[var(--surface-strong)] p-3"><CheckCircle2 size={15} className="mb-2 text-[var(--accent)]"/><p className="text-[10px] font-black uppercase tracking-wider text-[var(--muted)]">Completate</p><p className="text-lg font-black">{selectedSessions.filter(s=>s.completedAt).length}</p></div></div>}</aside></div></div></main>
}
