"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, ChevronLeft, ChevronRight, Check, Play, UserRound } from "lucide-react";

type Data = { plan: { id: string; name: string; templates: { id: string; dayNumber: number; name: string; estimatedMins: number | null; exercises: { id: string; sets: number; repMin: number; repMax: number; exercise: { name: string } }[] }[] } | null; sessions: { id: string; startedAt: string; completedAt: string | null }[]; nextTemplate: { id: string; dayNumber: number; name: string; estimatedMins: number | null; exercises: { id: string; sets: number; repMin: number; repMax: number; exercise: { name: string } }[] } | null };
const navItems = [["Dashboard", "/dashboard", BarChart3], ["Progress", "/progress", BarChart3], ["Calendario", "/calendar", CalendarDays], ["Profilo", "/profile", UserRound]] as const;
function sameDay(a: Date, b: Date) { return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate(); }
function monthDays(date: Date) { const first = new Date(date.getFullYear(), date.getMonth(), 1); const count = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); const offset = (first.getDay() + 6) % 7; return [...Array(offset).fill(null), ...Array.from({ length: count }, (_, i) => new Date(date.getFullYear(), date.getMonth(), i + 1))]; }

export default function CalendarPage() {
  const [date, setDate] = useState(new Date()); const [selected, setSelected] = useState(new Date()); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/auth/me").then(r => r.json()).then(d => { if (!d.user) window.location.href = "/login?next=/calendar"; else if (!d.user.onboarding?.completedAt) window.location.href = "/onboarding"; }); }, []);
  useEffect(() => { setLoading(true); fetch(`/api/workouts/dashboard?year=${date.getFullYear()}&month=${date.getMonth()}`).then(r => r.json()).then(setData).finally(() => setLoading(false)); }, [date]);
  const days = useMemo(() => monthDays(date), [date]); const today = new Date(); const selectedSession = data?.sessions.find(s => sameDay(new Date(s.startedAt), selected)); const template = data?.nextTemplate; const canStart = !!template && !selectedSession?.completedAt;
  return <main className="min-h-screen bg-[var(--background)] pb-28"><div className="mx-auto max-w-5xl px-5 py-6 sm:px-8"><header><p className="text-xs font-black tracking-[0.22em] text-[var(--accent)]">TRAINING CALENDAR</p><h1 className="mt-2 text-4xl font-black tracking-tight">Calendario</h1><p className="mt-2 text-sm text-[var(--muted)]">Scegli il giorno in cui vuoi allenarti.</p></header>
    <section className="mt-7 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-[var(--muted)]">{date.toLocaleDateString("it-IT", { month: "long", year: "numeric" })}</p><h2 className="mt-1 text-2xl font-black">{data?.plan?.name || "Nessun programma"}</h2></div><div className="flex items-center gap-2"><button aria-label="Mese precedente" onClick={() => setDate(new Date(date.getFullYear(), date.getMonth() - 1, 1))} className="rounded-xl border border-[var(--border)] p-2"><ChevronLeft size={18}/></button><button onClick={() => { const n = new Date(); setDate(n); setSelected(n); }} className="rounded-xl border border-[var(--border)] px-3 py-2 text-xs font-black">OGGI</button><button aria-label="Mese successivo" onClick={() => setDate(new Date(date.getFullYear(), date.getMonth() + 1, 1))} className="rounded-xl border border-[var(--border)] p-2"><ChevronRight size={18}/></button></div></div>
      <div className="mt-6 grid grid-cols-7 gap-1.5 text-center sm:gap-2">{["Lun","Mar","Mer","Gio","Ven","Sab","Dom"].map(d => <div key={d} className="py-2 text-[10px] font-black uppercase tracking-wider text-[var(--muted)]">{d}</div>)}{days.map((day, i) => { if (!day) return <div key={`empty-${i}`} className="min-h-16"/>; const session = data?.sessions.find(s => sameDay(new Date(s.startedAt), day)); const isSelected = sameDay(day, selected); const isToday = sameDay(day, today); return <button key={day.toISOString()} onClick={() => setSelected(day)} className={`relative min-h-16 rounded-2xl p-2 text-left transition ${isSelected ? "ring-2 ring-[var(--accent)]" : "border border-[var(--border)]"} ${isToday ? "bg-[var(--surface-strong)]" : "bg-[var(--background)]"}`}><span className="text-sm font-black">{day.getDate()}</span>{session?.completedAt ? <span className="absolute bottom-2 left-2 right-2 flex items-center justify-center gap-1 rounded-full bg-[var(--accent)] px-1 py-0.5 text-[8px] font-black text-[var(--accent-foreground)]"><Check size={10}/> COMPLETATO</span> : isToday ? <span className="absolute bottom-2 left-2 right-2 text-[9px] font-black text-[var(--accent)]">OGGI</span> : null}</button>; })}</div></section>
    <section className="mt-5 rounded-[2rem] bg-[var(--accent)] p-6 text-[var(--accent-foreground)] sm:p-7"><p className="text-xs font-black tracking-[0.18em] opacity-70">{sameDay(selected, today) ? "OGGI" : selected.toLocaleDateString("it-IT", { weekday: "long", day: "numeric", month: "long" }).toUpperCase()}</p><h2 className="mt-2 text-2xl font-black">{selectedSession?.completedAt ? "Allenamento completato" : template?.name || "Giorno libero"}</h2><p className="mt-2 text-sm font-medium opacity-75">{selectedSession?.completedAt ? "Hai già completato l'allenamento di questa giornata." : template ? `${template.exercises.length} esercizi${template.estimatedMins ? ` · circa ${template.estimatedMins} min` : ""}. Puoi iniziarlo quando vuoi.` : "Non hai ancora un programma attivo."}</p>{canStart && <Link href={`/workout?date=${selected.toISOString().slice(0,10)}&day=${template.dayNumber}`} className="mt-5 inline-flex items-center gap-2 rounded-2xl bg-[var(--accent-foreground)] px-5 py-3.5 text-sm font-black"><Play size={16} fill="currentColor"/> INIZIA ALLENAMENTO</Link>}</section>
    <section className="mt-5 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-5 sm:p-7"><p className="text-xs font-black tracking-wider text-[var(--accent)]">PROGRAMMA</p><div className="mt-4 space-y-2">{data?.plan?.templates.map(day => <div key={day.id} className="flex items-center justify-between rounded-2xl bg-[var(--surface-strong)] px-4 py-3"><div><p className="text-[10px] font-black uppercase text-[var(--muted)]">Giorno {day.dayNumber}</p><p className="font-black">{day.name}</p></div><span className="text-xs font-bold text-[var(--muted)]">{day.exercises.length} esercizi</span></div>)}</div>{loading && <p className="mt-3 text-sm text-[var(--muted)]">Caricamento...</p>}</section>
    <nav className="fixed inset-x-0 bottom-4 z-20 mx-auto flex w-[calc(100%-2rem)] max-w-md items-center justify-around rounded-3xl border border-[var(--border)] bg-[var(--surface)]/95 p-2 shadow-2xl backdrop-blur-xl">{navItems.map(([label, href, Icon]) => <Link key={label} href={href} className={`flex min-w-16 flex-col items-center gap-1 rounded-2xl px-3 py-2 text-[10px] font-bold ${href === "/calendar" ? "bg-[var(--accent)] text-[var(--accent-foreground)]" : "text-[var(--muted)]"}`}><Icon size={17}/>{label}</Link>)}</nav>
  </div></main>;
}
